### ISSUE TITLE
[FEATURE REQUEST]: Quest and PC filter for avatar searcher.

### ISSUE THREAD

**Issue by GuppySlushie** [emmVRC/emmVRC-Public#1692] opened 2022-06-13 09:05 UTC
### Is your feature request related to a problem? Please describe.

It’s really annoying whenever I’m trying to find an avatar for a quest friend, but the only results are pc. There might be one or two quest compatible avatars, but it’s not a guarantee.

### Describe the solution you'd like

The solution I’ve come up with is a filter to filter between PC only or Quest compatible avatars. 

### Describe alternatives you've considered

If that isn’t possible or an alternative is needed, a small counter to see how many quest and pc compatible avatars there are. For example, next to the avatar amount counter, it could say PC:[insert amount of pc avatars] and, Quest:[insert amount of quest avatars].

**Comment by BenjaminZehowlt** [comment] 2022-06-13 09:27
Duplicate of #1333

**Closed as completed by BenjaminZehowlt** 2022-06-13 09:27 UTC
Labels: feature
