### ISSUE TITLE
[Feature] Avatar search independent of emmVRC Favorites list

### ISSUE THREAD

**Issue by burritosoftware** [emmVRC/emmVRC-Public#1553] opened 2021-10-03 23:12 UTC
When disabling the emmVRC Favorites list, avatar search is disabled as well. The feature should be changed so emmVRC Favorites can be disabled while avatar search is still available. Avatar search can then be disabled through the emmVRC Network toggle.

**Comment by BenjaminZehowlt** [comment] 2022-07-17 06:04
Duplicate of #1511

**Closed by BenjaminZehowlt** 2022-07-17 06:04 UTC
