### ISSUE TITLE
[Bug] Avatar Selection makes whole game slow

### ISSUE THREAD

**Issue by v2elite** [emmVRC/emmVRC-Public#84] opened 2020-11-03 14:41 UTC
Hi, i have a emmVRC Avatar List with about 300 Avatars, when I open the window for selection my FPS drop from 60 fps to 10... I guess it is because not only the Icon of the visible avatars is preloaded but some more non needed information... would it be possible to load only the Avatars which are visible in the current view?

**Comment by rakosi2** [comment] 2020-11-04 10:05
Closing as it's a duplicate of #85

**Closed by rakosi2** 2020-11-04 10:05 UTC
Labels: duplicate
