### ISSUE TITLE
Emmvrc

### ISSUE THREAD

**Issue by MeadowVr** [emmVRC/emmVRC-Public#1681] opened 2022-05-26 17:37 UTC
the search avatar thing is not working

**Comment by Janni9009** [comment] 2022-05-26 18:06
Seems like a duplicate of #1678 
If you can't search by typing a name into the search field either, join the emmVRC [discord](https://discord.gg/emmvrc) and go to the help and support channels.

**Closed by Janni9009** 2022-05-26 18:06 UTC
Labels: duplicate, invalid
