### ISSUE TITLE
[FEATURE] SAVE SPEED VALUE IN CONFIG

### ISSUE THREAD

**Issue by TimoB2005** [emmVRC/emmVRC-Public#1518] opened 2021-07-13 11:08 UTC
Hey, can you save the speed value in a config and load it on start?

So nobody has to setting up their speed on start

:)
best regards

**Comment by rakosi2** [comment] 2021-07-19 19:32
I feel like this is a duplicate of #1323

**Closed** 2021-09-19 00:25 UTC
