### ISSUE TITLE
this button to view avatar authors isnt working

### ISSUE THREAD

**Issue by kenway101** [emmVRC/emmVRC-Public#1581] opened 2021-11-09 20:14 UTC
![20211109141026_1](https://user-images.githubusercontent.com/94015337/140997756-0d795b70-fa0c-4200-bf82-2ceeccbeb60d.jpg)
)

**Comment by rakosi2** [comment] 2021-11-09 20:16
Duplicate of #1570

**Closed by rakosi2** 2021-11-09 20:16 UTC
