### ISSUE TITLE
Bug: Unable to search in Japanese, Chinese, and Korean. You can search in English only.

### ISSUE THREAD

**Issue by jwmmmdo** [emmVRC/emmVRC-Public#1321] opened 2020-12-22 15:00 UTC
![나나치](https://user-images.githubusercontent.com/76485838/102901940-93881000-44b1-11eb-9660-059a45df1887.PNG)
![fgfdgfdg](https://user-images.githubusercontent.com/76485838/102901948-94b93d00-44b1-11eb-95db-a02f10034d36.PNG)
![bfd](https://user-images.githubusercontent.com/76485838/102901951-9551d380-44b1-11eb-9417-801985f5c997.PNG)

If you look at the current picture, there are avatars called Nanachi in Korean. These avatars used to be searchable before. But it doesn't come out now. There is an avatar called Nanachi in Japanese, but it doesn't come out.
But if you type it in English, you can find it.
It's uncomfortable because I can't search for avatar. Is it possible to resolve it?

**Comment by rakosi2** [comment] 2020-12-22 18:47
Closing as it's a duplicate of #1319

**Closed by rakosi2** 2020-12-22 18:47 UTC
Labels: duplicate
