### ISSUE TITLE
[FEATURE] Avatar Search Filters.

### ISSUE THREAD

**Issue by MortisThorne** [emmVRC/emmVRC-Public#1417] opened 2021-03-13 02:26 UTC
Could we get more options for the avatar searching mechanisms? Like a filter for newest-oldest/oldest-newest and alphabetic sorting. Also more capability for searching using special characters, especially because a lot of people are using abnormal characters in their usernames and avi names nowadays, so I'm always getting "your search could not be processed" even when searching straight from someone's profile.

**Comment by rakosi2** [comment] 2021-03-13 04:31
Seems like a duplicate of #1309. If it is different then just reopen this ticket.

**Closed by rakosi2** 2021-03-13 04:31 UTC
Labels: duplicate
