### ISSUE TITLE
Export Favourites

### ISSUE THREAD

**Issue by GenesisAria** [emmVRC/emmVRC-Public#1575] opened 2021-11-09 10:08 UTC
Favourites export seems to be broken.  No effect when exporting.

**Comment by rakosi2** [comment] 2021-11-09 19:07
The issue is known and we are working on it.

**Comment by thetrueyoshifan** [comment] 2021-11-11 07:20
Fixed as of emmVRC v3.0.2

**Closed by thetrueyoshifan** 2021-11-11 07:20 UTC
Labels: bug
