### ISSUE TITLE
[FEATURE] Speed option saver

### ISSUE THREAD

**Issue by WumpusBackup** [emmVRC/emmVRC-Public#1479] opened 2021-05-20 10:10 UTC
Everytime you join VRC now with emmVRC you would have to go into player tweaks and put the speed to whatever you like manually.
Instead it'd be nicer for it to just save and not have to reset it every time :)

**Comment by rakosi2** [comment] 2021-05-21 20:47
Sounds like a duplicate of #1323. Feel free to reopen if it not.

**Closed by rakosi2** 2021-05-21 20:47 UTC
