### ISSUE TITLE
White box by microphone icon

### ISSUE THREAD

**Issue by timingplanet** [emmVRC/emmVRC-Public#1578] opened 2021-11-09 17:20 UTC
Had a white box after updating emm by microphone icon I dismissed the update notification for emm and it was still there had to restart game to get rid of it due to nothing else working

**Comment by rakosi2** [comment] 2021-11-09 19:07
The issue is known and we are working on it.

**Comment by thetrueyoshifan** [comment] 2021-11-17 05:04
Fixed as of emmVRC v3.0.3

**Closed by thetrueyoshifan** 2021-11-17 05:04 UTC
Labels: bug
