### ISSUE TITLE
[BUG] Your Search Could not be processed error (Avatar Search)

### ISSUE THREAD

**Issue by ZingyZou** [emmVRC/emmVRC-Public#1397] opened 2021-02-21 12:59 UTC
When searching for avatars I sometimes get a "Your search could not be processed error". It seems to only happen when searching with things that have special characters/letters. For example, when searching avatars by a users name which has lots of weird symbols etc (including using the search avatars button in the emm functions on the users profile)

**Comment by loukylor** [comment] 2021-02-21 18:43
duplicate of #1319

**Closed** 2021-02-21 20:16 UTC
Labels: duplicate
