### ISSUE TITLE
[Feature] Sort avatars by quest friendly 

### ISSUE THREAD

**Issue by keevavr** [emmVRC/emmVRC-Public#1606] opened 2021-11-27 19:17 UTC
It would be nice to be able to sort the quest friendly from pc only avatars in favorites. A check box or additional sorting criteria :)

**Comment by otakuderk** [comment] 2022-01-18 16:02
Frl, was up from 7pm to 4am trying to find good quest avatars

**Comment by rakosi2** [comment] 2022-01-19 07:03
Duplicate of #1333

**Closed by rakosi2** 2022-01-19 07:03 UTC
