### ISSUE TITLE
[FEATURE] Quest and Pc avatar seacher

### ISSUE THREAD

**Issue by MochaBunnz** [emmVRC/emmVRC-Public#1641] opened 2022-03-08 14:15 UTC
Besides being able to look up avatars we should be also able to pick if we want to see only pc avatars, only quest avatars or both and only limit it to those seachers. So its easier if you want to find both quest/pc accesible avatars.

**Comment by kociorozeq** [comment] 2022-03-18 20:51
yeah pleaseee

**Comment by Quaxly** [comment] 2022-03-20 17:13
need this

**Comment by BenjaminZehowlt** [comment] 2022-06-03 06:59
Duplicate of #1333

**Closed by BenjaminZehowlt** 2022-06-03 06:59 UTC
