### ISSUE TITLE
[Bug Report] Error with the "users in room"

### ISSUE THREAD

**Issue by CaptainHydra719** [emmVRC/emmVRC-Public#1348] opened 2021-01-13 04:54 UTC
Says it not connected to the server, even though it is.
and it's showing this in the program window.
![Screenshot (4)](https://user-images.githubusercontent.com/77374790/104408161-4deebe00-5518-11eb-8000-bc0ff3e34a49.png)

**Comment by loukylor** [comment] 2021-01-13 04:56
Duplicate of #111

**Comment by rakosi2** [comment] 2021-01-13 04:56
same as #111 you have to have 'Show quick menu hud in desktop' disabled when starting up VRChat.

**Closed** 2021-01-13 05:46 UTC
Labels: duplicate
