### ISSUE TITLE
[Feature Request] Avatar Search Filtering by Platforms

### ISSUE THREAD

**Issue by Orakuruu** [emmVRC/emmVRC-Public#1543] opened 2021-09-03 05:33 UTC
It would be nice to be able to sort Avatar Search by platform, whether it be by Quest only, PC only, or both. Would also be nice to be able to remove any avatars that are "Not Available" in the search results.

**Comment by BenjaminZehowlt** [comment] 2022-06-03 06:58
Duplicate of #1333

**Closed by BenjaminZehowlt** 2022-06-03 06:58 UTC
