### ISSUE TITLE
[Feature] Filter avatar search by Quest-compatibility

### ISSUE THREAD

**Issue by IlexisTheMadcat** [emmVRC/emmVRC-Public#1634] opened 2022-02-24 21:14 UTC
I have a Quest 2 and I need more avatars to use on it; problem is, the ones I'm looking for are hard to find with the world search and most of the results in the avatar search are PC only and more than half that _are_ Quest compatible are set to private, so I can't even use it.

Two feature requests if you will:
1) Ability to filter avatar search for Quest-compatible avatars (Show only cross-platform)
2) Remove private avatars from search (Privates just don't load at all when you click "Change into Avatars", nothing happens).

Thank you in advance for considering!

**Comment by BenjaminZehowlt** [comment] 2022-06-03 06:58
Duplicate of #1333

**Closed by BenjaminZehowlt** 2022-06-03 06:58 UTC
