### ISSUE TITLE
Filters (feature)

### ISSUE THREAD

**Issue by MrWhatsit2you** [emmVRC/emmVRC-Public#1461] opened 2021-04-23 15:05 UTC
For the longest time about Emmvrc I always hated how difficult it was to search up avatars, while I was happy we can see whats quest compatable and whats not, what I dont like is how we dont have a filters option, like so we can see avatars that are not pc only if that makes sense, because with that, its easier to help others get avatars on quest and let everyone see their avatars, I cant make a good point, but I still highly suggest a pc/quest/BOTH filter could be added in, like how the ABC, DATE, and creator one was added, im sure it isnt that difficult if one was added already

**Comment by Ayelwen** [comment] 2021-09-13 01:21
I’m seeing a few submissions for the ability to apply filter in avatar search. I would like to add this is my biggest #1 complaint about emmvrc. I am a pc user but have quest friends. So I have a massive headache trying to use the search to find avatars that I can use and they can see.

**Comment by BenjaminZehowlt** [comment] 2022-06-03 06:58
Duplicate of #1333

**Closed by BenjaminZehowlt** 2022-06-03 06:58 UTC
Labels: feature
