### ISSUE TITLE
[BUG REPORT] Headlamp still on after world reload

### ISSUE THREAD

**Issue by NinjaKid90** [emmVRC/emmVRC-Public#1371] opened 2021-02-04 21:44 UTC
if you turn the headlamp on and then reload world, the lamp stays on, if you go to the button to turn it off, its set to off, despite being on. Game reload is the fix. 
Image proof:
![20210204162344_1](https://user-images.githubusercontent.com/75510324/106959149-46ca6280-6708-11eb-871c-f5be48fc6589.jpg)

**Comment by rakosi2** [comment] 2021-02-04 21:47
Duplicate of #1330

**Closed by rakosi2** 2021-02-04 21:47 UTC
Labels: duplicate
